"""create main tables

Revision ID: 403434447af6
Revises: 62c8b3476b3d
Create Date: 2022-08-18 11:58:39.352158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '403434447af6'
down_revision = '62c8b3476b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('railway_code', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('departure_station', sa.String(), nullable=True),
    sa.Column('sender_statement', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('destination_station', sa.String(), nullable=True),
    sa.Column('border_crossing_stations', sa.String(), nullable=True),
    sa.Column('railway_carriage', sa.String(), nullable=True),
    sa.Column('shipping_name', sa.String(), nullable=True),
    sa.Column('container_owner', sa.String(), nullable=True),
    sa.Column('container', sa.String(), nullable=True),
    sa.Column('type_of_packaging', sa.String(), nullable=True),
    sa.Column('number_of_seats', sa.String(), nullable=True),
    sa.Column('net', sa.String(), nullable=True),
    sa.Column('tara', sa.String(), nullable=True),
    sa.Column('gross', sa.String(), nullable=True),
    sa.Column('seals', sa.String(), nullable=True),
    sa.Column('seal_quantity', sa.String(), nullable=True),
    sa.Column('submerged', sa.String(), nullable=True),
    sa.Column('method_of_determining_mass', sa.String(), nullable=True),
    sa.Column('payment_of_legal_fees', sa.String(), nullable=True),
    sa.Column('carriers', sa.String(), nullable=True),
    sa.Column('documents_by_sender', sa.String(), nullable=True),
    sa.Column('additional_information', sa.String(), nullable=True),
    sa.Column('custom_seal', sa.String(), nullable=True),
    sa.Column('inspector_name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('file_draft', sa.String(), nullable=True),
    sa.Column('file_original', sa.String(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('railway_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('departure_station', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sender_statement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_station', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('border_crossing_stations', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('railway_carriage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipping_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('container_owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('container', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_packaging', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_of_seats', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('net', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tara', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gross', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seals', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seal_quantity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('submerged', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('method_of_determining_mass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_of_legal_fees', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('carriers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('documents_by_sender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_information', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('custom_seal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inspector_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_draft', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_original', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('train_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], name='app_train_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='app_pkey')
    )
    op.drop_table('smgs')
    # ### end Alembic commands ###
