"""changed name to unique

Revision ID: 4b691ad0f302
Revises: 403434447af6
Create Date: 2022-08-19 11:35:18.670352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b691ad0f302'
down_revision = '403434447af6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trains', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trains', type_='unique')
    # ### end Alembic commands ###
