"""added new fields

Revision ID: c7e1f7327a42
Revises: 4b691ad0f302
Create Date: 2022-08-29 15:39:23.205478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e1f7327a42'
down_revision = '4b691ad0f302'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smgs', sa.Column('container_type', sa.String(), nullable=True))
    op.add_column('smgs', sa.Column('container_type_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smgs', 'container_type_code')
    op.drop_column('smgs', 'container_type')
    # ### end Alembic commands ###
