"""added excel

Revision ID: f56e15172f66
Revises: 5007e5d1dba3
Create Date: 2022-09-05 10:02:56.187925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56e15172f66'
down_revision = '5007e5d1dba3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trains', sa.Column('excel_file', sa.String(), nullable=True))
    op.drop_column('trains', 'excel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trains', sa.Column('excel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trains', 'excel_file')
    # ### end Alembic commands ###
